# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'photoshop.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QVBoxLayout, QWidget)

from graphicview import GraphicView

class Ui_PhotoShop(object):
    def setupUi(self, PhotoShop):
        if not PhotoShop.objectName():
            PhotoShop.setObjectName(u"PhotoShop")
        PhotoShop.resize(841, 645)
        PhotoShop.setMouseTracking(False)
        self.actionOpen = QAction(PhotoShop)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(PhotoShop)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSaveAs = QAction(PhotoShop)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        self.actionCreate = QAction(PhotoShop)
        self.actionCreate.setObjectName(u"actionCreate")
        self.actionBitmap = QAction(PhotoShop)
        self.actionBitmap.setObjectName(u"actionBitmap")
        self.actionGray = QAction(PhotoShop)
        self.actionGray.setObjectName(u"actionGray")
        self.actionTwoTone = QAction(PhotoShop)
        self.actionTwoTone.setObjectName(u"actionTwoTone")
        self.actionIndexColor = QAction(PhotoShop)
        self.actionIndexColor.setObjectName(u"actionIndexColor")
        self.actionRGBColor = QAction(PhotoShop)
        self.actionRGBColor.setObjectName(u"actionRGBColor")
        self.actionCMYKColor = QAction(PhotoShop)
        self.actionCMYKColor.setObjectName(u"actionCMYKColor")
        self.actionLabColor = QAction(PhotoShop)
        self.actionLabColor.setObjectName(u"actionLabColor")
        self.actionMultiChannel = QAction(PhotoShop)
        self.actionMultiChannel.setObjectName(u"actionMultiChannel")
        self.action8Bit = QAction(PhotoShop)
        self.action8Bit.setObjectName(u"action8Bit")
        self.action16Bit = QAction(PhotoShop)
        self.action16Bit.setObjectName(u"action16Bit")
        self.action32Bit = QAction(PhotoShop)
        self.action32Bit.setObjectName(u"action32Bit")
        self.actionQuit = QAction(PhotoShop)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionColorTable = QAction(PhotoShop)
        self.actionColorTable.setObjectName(u"actionColorTable")
        self.actionBrightnessContrast = QAction(PhotoShop)
        self.actionBrightnessContrast.setObjectName(u"actionBrightnessContrast")
        self.actionColorScale = QAction(PhotoShop)
        self.actionColorScale.setObjectName(u"actionColorScale")
        self.actionCurve = QAction(PhotoShop)
        self.actionCurve.setObjectName(u"actionCurve")
        self.actionExposure = QAction(PhotoShop)
        self.actionExposure.setObjectName(u"actionExposure")
        self.actionNaturalSaturation = QAction(PhotoShop)
        self.actionNaturalSaturation.setObjectName(u"actionNaturalSaturation")
        self.actionColorSaturation = QAction(PhotoShop)
        self.actionColorSaturation.setObjectName(u"actionColorSaturation")
        self.actionColorBalance = QAction(PhotoShop)
        self.actionColorBalance.setObjectName(u"actionColorBalance")
        self.actionMonochrome = QAction(PhotoShop)
        self.actionMonochrome.setObjectName(u"actionMonochrome")
        self.actionPhotoFilters = QAction(PhotoShop)
        self.actionPhotoFilters.setObjectName(u"actionPhotoFilters")
        self.actionChannelMixer = QAction(PhotoShop)
        self.actionChannelMixer.setObjectName(u"actionChannelMixer")
        self.actionColorSearch = QAction(PhotoShop)
        self.actionColorSearch.setObjectName(u"actionColorSearch")
        self.actionInversion = QAction(PhotoShop)
        self.actionInversion.setObjectName(u"actionInversion")
        self.actionColorSeparation = QAction(PhotoShop)
        self.actionColorSeparation.setObjectName(u"actionColorSeparation")
        self.actionThresholds = QAction(PhotoShop)
        self.actionThresholds.setObjectName(u"actionThresholds")
        self.actionGradientMapping = QAction(PhotoShop)
        self.actionGradientMapping.setObjectName(u"actionGradientMapping")
        self.actionAvailableColors = QAction(PhotoShop)
        self.actionAvailableColors.setObjectName(u"actionAvailableColors")
        self.actionShadowHighlight = QAction(PhotoShop)
        self.actionShadowHighlight.setObjectName(u"actionShadowHighlight")
        self.actionHDRTone = QAction(PhotoShop)
        self.actionHDRTone.setObjectName(u"actionHDRTone")
        self.actionDecolorization = QAction(PhotoShop)
        self.actionDecolorization.setObjectName(u"actionDecolorization")
        self.actionColorMatching = QAction(PhotoShop)
        self.actionColorMatching.setObjectName(u"actionColorMatching")
        self.actionReplacementColor = QAction(PhotoShop)
        self.actionReplacementColor.setObjectName(u"actionReplacementColor")
        self.actionToneHomogenization = QAction(PhotoShop)
        self.actionToneHomogenization.setObjectName(u"actionToneHomogenization")
        self.centralwidget = QWidget(PhotoShop)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMouseTracking(False)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.graphicsView = GraphicView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setMouseTracking(False)

        self.verticalLayout.addWidget(self.graphicsView)

        PhotoShop.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(PhotoShop)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 841, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuImage = QMenu(self.menubar)
        self.menuImage.setObjectName(u"menuImage")
        self.menuMode = QMenu(self.menuImage)
        self.menuMode.setObjectName(u"menuMode")
        self.menu_Adjust = QMenu(self.menuImage)
        self.menu_Adjust.setObjectName(u"menu_Adjust")
        self.menuLayer = QMenu(self.menubar)
        self.menuLayer.setObjectName(u"menuLayer")
        self.menuWord = QMenu(self.menubar)
        self.menuWord.setObjectName(u"menuWord")
        self.menuSelect = QMenu(self.menubar)
        self.menuSelect.setObjectName(u"menuSelect")
        self.menuFilter = QMenu(self.menubar)
        self.menuFilter.setObjectName(u"menuFilter")
        self.menu3D = QMenu(self.menubar)
        self.menu3D.setObjectName(u"menu3D")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuPlugIns = QMenu(self.menubar)
        self.menuPlugIns.setObjectName(u"menuPlugIns")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        PhotoShop.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(PhotoShop)
        self.statusbar.setObjectName(u"statusbar")
        PhotoShop.setStatusBar(self.statusbar)
        self.dockWidget = QDockWidget(PhotoShop)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tabWidget = QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabColor = QWidget()
        self.tabColor.setObjectName(u"tabColor")
        self.tabWidget.addTab(self.tabColor, "")
        self.tabSwatches = QWidget()
        self.tabSwatches.setObjectName(u"tabSwatches")
        self.tabWidget.addTab(self.tabSwatches, "")
        self.tabGradient = QWidget()
        self.tabGradient.setObjectName(u"tabGradient")
        self.tabWidget.addTab(self.tabGradient, "")
        self.tabPattern = QWidget()
        self.tabPattern.setObjectName(u"tabPattern")
        self.tabWidget.addTab(self.tabPattern, "")

        self.verticalLayout_2.addWidget(self.tabWidget)

        self.dockWidget.setWidget(self.dockWidgetContents)
        PhotoShop.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget)
        self.dockWidget_2 = QDockWidget(PhotoShop)
        self.dockWidget_2.setObjectName(u"dockWidget_2")
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        PhotoShop.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget_2)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuLayer.menuAction())
        self.menubar.addAction(self.menuWord.menuAction())
        self.menubar.addAction(self.menuSelect.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menu3D.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPlugIns.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionCreate)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuImage.addAction(self.menuMode.menuAction())
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.menu_Adjust.menuAction())
        self.menuMode.addAction(self.actionBitmap)
        self.menuMode.addAction(self.actionGray)
        self.menuMode.addAction(self.actionTwoTone)
        self.menuMode.addAction(self.actionIndexColor)
        self.menuMode.addAction(self.actionRGBColor)
        self.menuMode.addAction(self.actionCMYKColor)
        self.menuMode.addAction(self.actionLabColor)
        self.menuMode.addAction(self.actionMultiChannel)
        self.menuMode.addSeparator()
        self.menuMode.addAction(self.action8Bit)
        self.menuMode.addAction(self.action16Bit)
        self.menuMode.addAction(self.action32Bit)
        self.menuMode.addSeparator()
        self.menuMode.addAction(self.actionColorTable)
        self.menu_Adjust.addAction(self.actionBrightnessContrast)
        self.menu_Adjust.addAction(self.actionColorScale)
        self.menu_Adjust.addAction(self.actionCurve)
        self.menu_Adjust.addAction(self.actionExposure)
        self.menu_Adjust.addSeparator()
        self.menu_Adjust.addAction(self.actionNaturalSaturation)
        self.menu_Adjust.addAction(self.actionColorSaturation)
        self.menu_Adjust.addAction(self.actionColorBalance)
        self.menu_Adjust.addAction(self.actionMonochrome)
        self.menu_Adjust.addAction(self.actionPhotoFilters)
        self.menu_Adjust.addAction(self.actionChannelMixer)
        self.menu_Adjust.addAction(self.actionColorSearch)
        self.menu_Adjust.addSeparator()
        self.menu_Adjust.addAction(self.actionInversion)
        self.menu_Adjust.addAction(self.actionColorSeparation)
        self.menu_Adjust.addAction(self.actionThresholds)
        self.menu_Adjust.addAction(self.actionGradientMapping)
        self.menu_Adjust.addAction(self.actionAvailableColors)
        self.menu_Adjust.addSeparator()
        self.menu_Adjust.addAction(self.actionShadowHighlight)
        self.menu_Adjust.addAction(self.actionHDRTone)
        self.menu_Adjust.addSeparator()
        self.menu_Adjust.addAction(self.actionDecolorization)
        self.menu_Adjust.addAction(self.actionColorMatching)
        self.menu_Adjust.addAction(self.actionReplacementColor)
        self.menu_Adjust.addAction(self.actionToneHomogenization)

        self.retranslateUi(PhotoShop)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(PhotoShop)
    # setupUi

    def retranslateUi(self, PhotoShop):
        PhotoShop.setWindowTitle(QCoreApplication.translate("PhotoShop", u"Photoshop", None))
#if QT_CONFIG(tooltip)
        PhotoShop.setToolTip(QCoreApplication.translate("PhotoShop", u"Photoshop", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpen.setText(QCoreApplication.translate("PhotoShop", u"\u6253\u5f00(O)", None))
        self.actionSave.setText(QCoreApplication.translate("PhotoShop", u"\u5b58\u50a8(S)", None))
        self.actionSaveAs.setText(QCoreApplication.translate("PhotoShop", u"\u5b58\u50a8\u4e3a(A)", None))
#if QT_CONFIG(tooltip)
        self.actionSaveAs.setToolTip(QCoreApplication.translate("PhotoShop", u"\u5b58\u50a8\u4e3a(A)", None))
#endif // QT_CONFIG(tooltip)
        self.actionCreate.setText(QCoreApplication.translate("PhotoShop", u"\u65b0\u5efa(N)", None))
        self.actionBitmap.setText(QCoreApplication.translate("PhotoShop", u"\u4f4d\u56fe(B)", None))
        self.actionGray.setText(QCoreApplication.translate("PhotoShop", u"\u7070\u5ea6(G)", None))
        self.actionTwoTone.setText(QCoreApplication.translate("PhotoShop", u"\u53cc\u8272\u8c03(D)", None))
        self.actionIndexColor.setText(QCoreApplication.translate("PhotoShop", u"\u7d22\u5f15\u989c\u8272(I)", None))
        self.actionRGBColor.setText(QCoreApplication.translate("PhotoShop", u"RGB\u989c\u8272(R)", None))
        self.actionCMYKColor.setText(QCoreApplication.translate("PhotoShop", u"CMYK\u989c\u8272(C)", None))
        self.actionLabColor.setText(QCoreApplication.translate("PhotoShop", u"Lab\u989c\u8272(L)", None))
        self.actionMultiChannel.setText(QCoreApplication.translate("PhotoShop", u"\u591a\u901a\u9053(M)", None))
        self.action8Bit.setText(QCoreApplication.translate("PhotoShop", u"8\u4f4d/\u901a\u9053(A)", None))
        self.action16Bit.setText(QCoreApplication.translate("PhotoShop", u"16\u4f4d/\u901a\u9053(N)", None))
        self.action32Bit.setText(QCoreApplication.translate("PhotoShop", u"32\u4f4d/\u901a\u9053(H)", None))
        self.actionQuit.setText(QCoreApplication.translate("PhotoShop", u"\u9000\u51fa(Q)", None))
        self.actionColorTable.setText(QCoreApplication.translate("PhotoShop", u"\u989c\u8272\u8868(T)", None))
        self.actionBrightnessContrast.setText(QCoreApplication.translate("PhotoShop", u"\u4eae\u5ea6/\u5bf9\u6bd4\u5ea6(C)", None))
        self.actionColorScale.setText(QCoreApplication.translate("PhotoShop", u"\u8272\u9636(L)", None))
        self.actionCurve.setText(QCoreApplication.translate("PhotoShop", u"\u66f2\u7ebf(U)", None))
        self.actionExposure.setText(QCoreApplication.translate("PhotoShop", u"\u66dd\u5149\u5ea6(E)", None))
        self.actionNaturalSaturation.setText(QCoreApplication.translate("PhotoShop", u"\u81ea\u7136\u9971\u548c\u5ea6(V)", None))
        self.actionColorSaturation.setText(QCoreApplication.translate("PhotoShop", u"\u8272\u76f8/\u9971\u548c\u5ea6(H)", None))
        self.actionColorBalance.setText(QCoreApplication.translate("PhotoShop", u"\u8272\u5f69\u5e73\u8861(B)", None))
        self.actionMonochrome.setText(QCoreApplication.translate("PhotoShop", u"\u9ed1\u767d(B)", None))
        self.actionPhotoFilters.setText(QCoreApplication.translate("PhotoShop", u"\u7167\u7247\u6ee4\u955c(F)", None))
        self.actionChannelMixer.setText(QCoreApplication.translate("PhotoShop", u"\u901a\u9053\u6df7\u5408\u5668(X)", None))
        self.actionColorSearch.setText(QCoreApplication.translate("PhotoShop", u"\u989c\u8272\u67e5\u627e", None))
        self.actionInversion.setText(QCoreApplication.translate("PhotoShop", u"\u53cd\u76f8(I)", None))
        self.actionColorSeparation.setText(QCoreApplication.translate("PhotoShop", u"\u8272\u8c03\u5206\u79bb(P)", None))
        self.actionThresholds.setText(QCoreApplication.translate("PhotoShop", u"\u9608\u503c(T)", None))
        self.actionGradientMapping.setText(QCoreApplication.translate("PhotoShop", u"\u6e10\u53d8\u6620\u5c04(G)", None))
        self.actionAvailableColors.setText(QCoreApplication.translate("PhotoShop", u"\u53ef\u9009\u989c\u8272(S)", None))
        self.actionShadowHighlight.setText(QCoreApplication.translate("PhotoShop", u"\u9634\u5f71/\u9ad8\u5149(W)", None))
        self.actionHDRTone.setText(QCoreApplication.translate("PhotoShop", u"HDR\u8272\u8c03", None))
        self.actionDecolorization.setText(QCoreApplication.translate("PhotoShop", u"\u53bb\u8272(D)", None))
        self.actionColorMatching.setText(QCoreApplication.translate("PhotoShop", u"\u5339\u914d\u989c\u8272(M)", None))
        self.actionReplacementColor.setText(QCoreApplication.translate("PhotoShop", u"\u66ff\u6362\u989c\u8272(R)", None))
        self.actionToneHomogenization.setText(QCoreApplication.translate("PhotoShop", u"\u8272\u8c03\u5747\u5316(Q)", None))
        self.menuFile.setTitle(QCoreApplication.translate("PhotoShop", u"\u6587\u4ef6(F)", None))
        self.menuEdit.setTitle(QCoreApplication.translate("PhotoShop", u"\u7f16\u8f91(E)", None))
        self.menuImage.setTitle(QCoreApplication.translate("PhotoShop", u"\u56fe\u50cf(I)", None))
        self.menuMode.setTitle(QCoreApplication.translate("PhotoShop", u"\u6a21\u5f0f(M)", None))
        self.menu_Adjust.setTitle(QCoreApplication.translate("PhotoShop", u"\u8c03\u6574(J)", None))
        self.menuLayer.setTitle(QCoreApplication.translate("PhotoShop", u"\u56fe\u5c42(L)", None))
        self.menuWord.setTitle(QCoreApplication.translate("PhotoShop", u"\u6587\u5b57(Y)", None))
        self.menuSelect.setTitle(QCoreApplication.translate("PhotoShop", u"\u9009\u62e9(S)", None))
        self.menuFilter.setTitle(QCoreApplication.translate("PhotoShop", u"\u6ee4\u955c(T)", None))
        self.menu3D.setTitle(QCoreApplication.translate("PhotoShop", u"3D(D)", None))
        self.menuView.setTitle(QCoreApplication.translate("PhotoShop", u"\u89c6\u56fe(V)", None))
        self.menuPlugIns.setTitle(QCoreApplication.translate("PhotoShop", u"\u589e\u6548\u5de5\u5177", None))
        self.menuWindow.setTitle(QCoreApplication.translate("PhotoShop", u"\u7a97\u53e3(W)", None))
        self.menuHelp.setTitle(QCoreApplication.translate("PhotoShop", u"\u5e2e\u52a9(H)", None))
#if QT_CONFIG(accessibility)
        self.tabColor.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabColor), QCoreApplication.translate("PhotoShop", u"\u989c\u8272", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSwatches), QCoreApplication.translate("PhotoShop", u"\u8272\u677f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGradient), QCoreApplication.translate("PhotoShop", u"\u6e10\u53d8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPattern), QCoreApplication.translate("PhotoShop", u"\u56fe\u6848", None))
    # retranslateUi

